global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Mvc;
global using network_project.Models;
global using network_project.Dto;
global using network_project.Interfaces;
global using network_project.Helper;